### ISSUE TITLE
What is a good scrolling effect in react? 

### ISSUE THREAD

**Issue by prince0010** [prince0010/final_Port#2]

**Comment by kij4040** [comment]
Hi, I don't know if this can help but there is a scrolling in react
just try this one
'npm i react-scroll' 
and if you want like motion effects 
you can try 'Framer Motions and React-Motions' its good tho. 
I hope it can help

**Comment by prince0010** [comment]
> Hi, I don't know if this can help but there is a scrolling in react just try this one 'npm i react-scroll' and if you want like motion effects you can try 'Framer Motions and React-Motions' its good tho. I hope it can help

oh wow, I will definitely try this, I didn't expect a fast reply tho Hahahah, thanks!
I already know about those motions and I want to try it soon tho! Thanks for that suggestions!

**Comment by kij4040** [comment]
> > Hi, I don't know if this can help but there is a scrolling in react just try this one 'npm i react-scroll' and if you want like motion effects you can try 'Framer Motions and React-Motions' its good tho. I hope it can help
> 
> oh wow, I will definitely try this, I didn't expect a fast reply tho Hahahah, thanks! I already know about those motions and I want to try it soon tho! Thanks for that suggestions!

Welcome!!!
